### PR TITLE
Track 7: Introduction to UI assignment

### LINKED ISSUE #5: Track 7: Introduction to UI assignment
TODOs:

- [x] Instructions assignment
- [x] Flexbox Froggy
- [x] Integration with API
- [x] Deploying on S3
- [x] Addition of Github login
- [x] Bonus: Github action to deploy website to AWS S3 on each code change
- [x] Improvements on UI

### PR DESCRIPTION
**Pull request by subhang-ti**

### CODE REVIEW

**Comment by subhang-ti** [comment]
Closes #5

**Comment by kushal-ti** [comment]
You've added an GH action but i don't see the corrosponding secrets in your Repo

**Comment by kushal-ti** [comment]
Also you action runs on push to master ......you don't have a master branch my man

**Comment by subhang-ti** [comment]
> Also you action runs on push to master ......you don't have a master branch my man
Sorry forgot about that
Changed it to main

**Review by sirjan-cn — CHANGES_REQUESTED** [review]
GitHub OAuth Missing, rest LGTM

**Comment by sirjan-cn** [comment]
@subhang-ti GitHub Oauth?

**Review by sirjan-cn — APPROVED** [review]

**Pull request merged**
